# syntax=docker/dockerfile:1.4

FROM rust:1.89.0-trixie AS base

WORKDIR /app

# Install required dependencies
RUN apt-get update && apt-get install -y \
    curl \
    clang \
    build-essential \
    git \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install SP1
RUN curl -L https://sp1.succinct.xyz | bash && \
    ~/.sp1/bin/sp1up && \
    ~/.sp1/bin/cargo-prove prove --version

FROM base AS builder

WORKDIR /app

COPY . .

# Build the cost-estimator
RUN cargo build --release --bin cost-estimator --features eigenda
# Build the game-monitor
RUN cargo build --release --bin game-monitor

# Runtime stage
FROM rust:1.89.0-trixie 

WORKDIR /app

# Copy the built binaries
COPY --from=builder /usr/src/app/target/release/cost-estimator /usr/local/bin/
COPY --from=builder /usr/src/app/target/release/game-monitor /usr/local/bin/

# Copy the entire workspace so we can run cargo_metadata::MetadataCommand to get the workspace root.
COPY . .
