[package]
name = "op-succinct-estimator"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
# local
op-succinct-host-utils.workspace = true
op-succinct-proof-utils.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-common.workspace = true
op-succinct-celestia-host-utils = { workspace = true, optional = true }
op-succinct-eigenda-host-utils = { workspace = true, optional = true }
op-succinct-ethereum-host-utils = { workspace = true, optional = true }

# sp1
sp1-sdk.workspace = true

# general
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
bincode.workspace = true
rkyv.workspace = true
tokio.workspace = true
tracing.workspace = true
futures.workspace = true
alloy-primitives.workspace = true

[dev-dependencies]
tempfile.workspace = true
rstest = "0.26"

[features]
default = ["ethereum"]
celestia = ["op-succinct-celestia-host-utils", "op-succinct-proof-utils/celestia"]
eigenda = ["op-succinct-eigenda-host-utils", "op-succinct-proof-utils/eigenda"]
ethereum = ["op-succinct-ethereum-host-utils", "op-succinct-proof-utils/ethereum"]
