# syntax=docker/dockerfile:1.4

FROM rust:1.89.0-trixie AS base

WORKDIR /app

# Install required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    clang \
    build-essential \
    git \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install SP1
RUN curl -L https://sp1.succinct.xyz | bash && \
    ~/.sp1/bin/sp1up && \
    ~/.sp1/bin/cargo-prove prove --version


FROM base AS chef
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo install cargo-chef --locked \
    && cargo install sccache --locked

ENV RUSTC_WRAPPER=/usr/local/cargo/bin/sccache \
    SCCACHE_DIR=/usr/local/cargo/sccache

FROM chef AS planner
COPY . .
RUN --mount=type=cache,id=rustup,target=/usr/local/rustup \
    --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /app

COPY rust-toolchain.toml rust-toolchain.toml
COPY --from=planner /app/recipe.json recipe.json

RUN --mount=type=cache,id=rustup,target=/usr/local/rustup \
    --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=sccache,target=/usr/local/cargo/sccache \
    cargo chef cook --release --recipe-path recipe.json

COPY . .

# Build the binary
RUN --mount=type=cache,id=rustup,target=/usr/local/rustup \
    --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=sccache,target=/usr/local/cargo/sccache \
    set -eux; \
    cargo build --release --bin challenger --features eigenda; \
    install -Dm755 target/release/challenger /out/challenger; \
    sccache --show-stats

# Runtime stage
FROM rust:1.89.0-trixie AS runtime

WORKDIR /app
COPY resources/ ./resources/

# Copy the built challenger binary
COPY --from=builder /out/challenger /usr/local/bin/challenger

# Set the command
CMD ["challenger"]
