name: Cargo Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2  
    - name: Test
      run: cargo test --release -- --skip e2e --skip test_proposer_defends_successfully --skip test_cycle_count_diff --skip test_post_to_github
      env:
        L2_NODE_RPC: ${{ secrets.L2_NODE_RPC }} # TODO: set proper RPCs in secret to run the tests
        L1_RPC: ${{ secrets.L1_RPC }}
        L1_BEACON_RPC: ${{ secrets.L1_BEACON_RPC }}
        L2_RPC: ${{ secrets.L2_RPC }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POST_TO_GITHUB: ${{ github.event_name == 'pull_request' }}
